SET SERVEROUTPUT ON;

EXECUTE NUEVO_PASE('PS4');
EXECUTE NUEVO_PASE('PC');
EXECUTE NUEVO_PASE('Switch');

EXECUTE NUEVO_CONSUMIBLE('Nachos','Comida');
EXECUTE NUEVO_CONSUMIBLE('Bepis','Bebida generica');
EXECUTE NUEVO_CONSUMIBLE('Cerveza','Bebida alcoholica');

EXECUTE NUEVO_BONO('Bono PS4 + Switch',5,'FALSE');
EXECUTE INTRODUCIR_PASE_EN_BONO(1,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(1,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(1,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(1,1);

EXECUTE INTRODUCIR_PASE_EN_BONO(3,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,1);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,1);


EXECUTE BONO_DISPONIBLE(1);

EXECUTE NUEVO_BONO('Bono Bepis',4,'FALSE');
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(1,2);
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,2);
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,2); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,2); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,2); 

EXECUTE BONO_DISPONIBLE(2);

EXECUTE NUEVO_BONO('Bono Gamer',9,'FALSE');
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,3);

EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);
EXECUTE INTRODUCIR_PASE_EN_BONO(2,3);

EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(3,3); 
EXECUTE BONO_DISPONIBLE(3);

EXECUTE NUEVO_BONO('Bono Void',0,'FALSE');
EXECUTE BONO_DISPONIBLE(4);

EXECUTE NUEVO_BONO('Bono Invisible',12,'FALSE');
EXECUTE INTRODUCIR_PASE_EN_BONO(3,5);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,5);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,5);
EXECUTE INTRODUCIR_PASE_EN_BONO(3,5);

EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 
EXECUTE INTRODUCIR_CONSUMIBLE_EN_BONO(2,5); 


EXECUTE NUEVO_USUARIO('12345678A', 'Ivan', '$2y$10$qmMtO6BMrRIazwkGtR4ujuKkc68QjS.IYvuXwB2j7podPedEQUvxS', 'Virdi22@gmail.com', TO_DATE ('1999/04/17','yyyy/mm/dd'), 'Tarjeta');
--Pass: PassDeIvan1

EXECUTE NUEVO_USUARIO('22345678B', 'Moises', '$2y$10$SK04FleGjKpdSONLWIl3gODxamOoGktr8roNmStdlp0iHE4ny85Zy', 'Subway@hotmail.com', TO_DATE ('1999/12/20','yyyy/mm/dd'), 'Tarjeta');
--Pass: PassDeMoises1

EXECUTE NUEVO_USUARIO('33345678C', 'Cote', '$2y$10$3IZN4ma1iIEzOdKk51t5nua5MYpH8Jpr160kbLP988/uUsLvu.GPa', 'SadCat@yahoo.com', TO_DATE ('1999/06/29','yyyy/mm/dd'), 'Paypal');
--Pass: PassDeCote1

EXECUTE NUEVO_USUARIO('44445678D', 'Dorian', '$2y$10$SijYKzObc0yYYtbuIouwLu8T4aqRZWlEf0ONvnMFrNGsoiJWtnvUu', 'SrPavus@gmail.com', TO_DATE ('1983/10/25','yyyy/mm/dd'), 'Tarjeta');
--Pass: Pavussss1

EXECUTE NUEVO_USUARIO('55555678E', 'Moriarty', '$2y$10$vCtqAiVcB0au97XN0HeRNe5o3ZlOd3rkD7Osj7mqZYwDhjSOksLU.', 'ArcherOfShinjuku@gmail.com', TO_DATE ('1973/06/15','yyyy/mm/dd'), 'Tarjeta');
--Pass: Archerrrr1

EXECUTE NUEVO_USUARIO('00000000F', 'Usuario de Baja', '$2y$10$hAecBmNEO95Yyr0ONzai7.BNCEKlibDFdliQp7f5M.Bh1eaGRWuoK', 'Baja@gmail.com', TO_DATE ('1999/02/19','yyyy/mm/dd'), 'Paypal');
--Pass: PassDeBaja1

EXECUTE NUEVO_USUARIO('00000000A', 'Admin', '$2y$10$BVE19UL.QmgOpKxR5l6v5uBfSiiibDCClqjtx7iVpZBVUHdUcIpYC', 'admin@admin.admin', TO_DATE ('1999/02/19','yyyy/mm/dd'), 'Paypal');
--Pass: ADMINadmin1


EXECUTE NUEVO_TORNEO(3,'Yugioh',70,'Torneo Yugioh', TO_DATE ('2019/06/25','yyyy/mm/dd'));
EXECUTE NUEVO_TORNEO(10,'Pokemon 30',250,'Torneo Pokemon USUM', TO_DATE ('2019/10/29','yyyy/mm/dd'));
EXECUTE NUEVO_TORNEO(5,'Puyo Puyo Tetris',100,'Torneo Puyo Puyo', TO_DATE ('2019/11/02','yyyy/mm/dd'));

EXECUTE INSCRIPCION('12345678A',1);
EXECUTE INSCRIPCION('22345678B',1);

EXECUTE INSCRIPCION('12345678A',3);
EXECUTE INSCRIPCION('33345678C',3);
EXECUTE INSCRIPCION('55555678E',3);

EXECUTE NUEVA_VENTA('12345678A');
EXECUTE INTRODUCIR_LINEA_VENTA(3,1,1,0);  
EXECUTE FINALIZAR_VENTA(1);

EXECUTE DARSE_BAJA('00000000F');

EXECUTE NUEVO_JUEGO_MESA('Jungle speed');
EXECUTE DONACION('12345678A', 'Jungle speed', 50);
EXECUTE DONACION('12345678A', 'Patatoide', 120);

COMMIT WORK;